# Generated by Django 2.0.6 on 2018-06-11 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generic_name', models.CharField(max_length=70)),
                ('brand_name', models.CharField(max_length=70)),
                ('physical_form', models.CharField(max_length=70)),
                ('pack_size', models.IntegerField()),
                ('price', models.IntegerField()),
                ('date_added', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'drugs',
                'verbose_name': 'drug',
            },
        ),
    ]
